### ISSUE TITLE
package is massive

### ISSUE THREAD

**Issue by okwme** [web3connect/web3connect#64]
1.92 MB
![screenshot_5](https://user-images.githubusercontent.com/964052/63296364-34b7f280-c2cf-11e9-9fd5-9641a9d21eab.png)

**Comment by pedrouid** [comment]
I know 🤦‍♂ This is because the library was originally intended to be used with React and then I just wrapped it around vanilla JS and had to add react-dom as dependency. 

I think the quickest solution right now is to use Preact as dependency instead and in the future we can use Svelte to compile all to vanilla JS

**Comment by pedrouid** [comment]
Fixed on v1.0.0-beta.20

**Comment by futantan** [comment]
> I know 🤦‍♂ This is because the library was originally intended to be used with React and then I just wrapped it around vanilla JS and had to add react-dom as dependency.
> 
> I think the quickest solution right now is to use Preact as dependency instead and in the future we can use Svelte to compile all to vanilla JS

Is there any plan to migrate to Svelte?
