### ISSUE TITLE
Is there a .js compilation for not requiring NodeJS?

### ISSUE THREAD

**Issue by DaniellMesquita** [web3connect/web3connect#97]
@crisgarner @pedrouid

**Comment by pedrouid** [comment]
Hi @DaniellMesquita, you can get the latest javascript bundle from the releases page.

https://github.com/web3connect/web3connect/releases

Beware that since we are using esmodules as a target with webpack, you will have to access the library from the window as `window.Web3Connect.default`, see example below:

**index.html**
```html
<script src="./web3connect/index.js"></script>
```

**script.js**
```javascript
const Web3Connect = window.Web3Connect.default
